FROM golang:latest

WORKDIR /api

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN go install github.com/githubnemo/CompileDaemon@latest && go mod tidy

COPY . .

EXPOSE 5000

ENTRYPOINT CompileDaemon -build="go build -o server ./cmd/api/" -command="./server --postgres"
