version: "3"
services:
  go-docker:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./:/api

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
